/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package longpipes;

import javax.swing.*;

/**
 *
 * @author up769662
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradeGroup = new javax.swing.ButtonGroup();
        colourGroup = new javax.swing.ButtonGroup();
        insulationGroup = new javax.swing.ButtonGroup();
        reinforcementGroup = new javax.swing.ButtonGroup();
        resistanceGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        PipeLengthTxtBox = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        PipeDiameterTxtBox = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Grade1RadioBtn = new javax.swing.JRadioButton();
        Grade2RadioBtn = new javax.swing.JRadioButton();
        Grade3RadioBtn = new javax.swing.JRadioButton();
        Grade4RadioBtn = new javax.swing.JRadioButton();
        Grade5RadioBtn = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        Color0RadioBtn = new javax.swing.JRadioButton();
        Color1RadioBtn = new javax.swing.JRadioButton();
        Color2RadioBtn = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        InsulationYes = new javax.swing.JRadioButton();
        InsulationNo = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        ChemicalResistanceYes = new javax.swing.JRadioButton();
        ChemicalResistanceNo = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        ReinforcementYes = new javax.swing.JRadioButton();
        ReinforcementNo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        removeOrder = new javax.swing.JButton();
        addOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PipeQuantityTxtBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Length (metres)"));
        jPanel2.setName("Length (metres)"); // NOI18N

        PipeLengthTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PipeLengthTxtBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PipeLengthTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PipeLengthTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Outer Diameter (inches)"));

        PipeDiameterTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PipeDiameterTxtBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PipeDiameterTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PipeDiameterTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Plastic Grade"));

        gradeGroup.add(Grade1RadioBtn);
        Grade1RadioBtn.setText("1");
        Grade1RadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grade1RadioBtnActionPerformed(evt);
            }
        });

        gradeGroup.add(Grade2RadioBtn);
        Grade2RadioBtn.setText("2");
        Grade2RadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grade2RadioBtnActionPerformed(evt);
            }
        });

        gradeGroup.add(Grade3RadioBtn);
        Grade3RadioBtn.setText("3");
        Grade3RadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grade3RadioBtnActionPerformed(evt);
            }
        });

        gradeGroup.add(Grade4RadioBtn);
        Grade4RadioBtn.setText("4");
        Grade4RadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grade4RadioBtnActionPerformed(evt);
            }
        });

        gradeGroup.add(Grade5RadioBtn);
        Grade5RadioBtn.setText("5");
        Grade5RadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grade5RadioBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Grade1RadioBtn)
                .addGap(18, 18, 18)
                .addComponent(Grade2RadioBtn)
                .addGap(18, 18, 18)
                .addComponent(Grade3RadioBtn)
                .addGap(18, 18, 18)
                .addComponent(Grade4RadioBtn)
                .addGap(18, 18, 18)
                .addComponent(Grade5RadioBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Grade5RadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Grade4RadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Grade3RadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Grade2RadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Grade1RadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Colour"));

        colourGroup.add(Color0RadioBtn);
        Color0RadioBtn.setText("No Colour");

        colourGroup.add(Color1RadioBtn);
        Color1RadioBtn.setText("1 Colour");
        Color1RadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Color1RadioBtnActionPerformed(evt);
            }
        });

        colourGroup.add(Color2RadioBtn);
        Color2RadioBtn.setText("2 Colours");
        Color2RadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Color2RadioBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Color0RadioBtn)
                .addGap(18, 18, 18)
                .addComponent(Color1RadioBtn)
                .addGap(18, 18, 18)
                .addComponent(Color2RadioBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Color0RadioBtn)
                    .addComponent(Color1RadioBtn)
                    .addComponent(Color2RadioBtn))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Inner Insulation"));

        insulationGroup.add(InsulationYes);
        InsulationYes.setText("Yes");
        InsulationYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsulationYesActionPerformed(evt);
            }
        });

        insulationGroup.add(InsulationNo);
        InsulationNo.setText("No");
        InsulationNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsulationNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InsulationYes)
                .addGap(32, 32, 32)
                .addComponent(InsulationNo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsulationYes)
                    .addComponent(InsulationNo))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Chemical Resistance"));

        resistanceGroup.add(ChemicalResistanceYes);
        ChemicalResistanceYes.setText("Yes");
        ChemicalResistanceYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChemicalResistanceYesActionPerformed(evt);
            }
        });

        resistanceGroup.add(ChemicalResistanceNo);
        ChemicalResistanceNo.setText("No");
        ChemicalResistanceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChemicalResistanceNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ChemicalResistanceYes)
                .addGap(28, 28, 28)
                .addComponent(ChemicalResistanceNo)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChemicalResistanceYes)
                    .addComponent(ChemicalResistanceNo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Outer Reinforcement "));

        reinforcementGroup.add(ReinforcementYes);
        ReinforcementYes.setText("Yes");
        ReinforcementYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReinforcementYesActionPerformed(evt);
            }
        });

        reinforcementGroup.add(ReinforcementNo);
        ReinforcementNo.setText("No");
        ReinforcementNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReinforcementNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ReinforcementYes)
                .addGap(29, 29, 29)
                .addComponent(ReinforcementNo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReinforcementYes)
                    .addComponent(ReinforcementNo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jList1);

        removeOrder.setText("Remove Order");
        removeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeOrderActionPerformed(evt);
            }
        });

        addOrder.setText("Add Order");

        jLabel1.setText("LongPipes Pipe Ordering System");

        PipeQuantityTxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PipeQuantityTxtBox.setText("pip quant (1..100)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(PipeQuantityTxtBox)
                        .addGap(18, 18, 18)
                        .addComponent(addOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(removeOrder)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PipeQuantityTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PipeLengthTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PipeLengthTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PipeLengthTxtBoxActionPerformed

    private void PipeDiameterTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PipeDiameterTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PipeDiameterTxtBoxActionPerformed

    private void Grade1RadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grade1RadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Grade1RadioBtnActionPerformed

    private void Grade2RadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grade2RadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Grade2RadioBtnActionPerformed

    private void Grade3RadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grade3RadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Grade3RadioBtnActionPerformed

    private void Grade4RadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grade4RadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Grade4RadioBtnActionPerformed

    private void Grade5RadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grade5RadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Grade5RadioBtnActionPerformed

    private void Color1RadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Color1RadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Color1RadioBtnActionPerformed

    private void Color2RadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Color2RadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Color2RadioBtnActionPerformed

    private void InsulationYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsulationYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsulationYesActionPerformed

    private void ReinforcementYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReinforcementYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReinforcementYesActionPerformed

    private void ChemicalResistanceYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChemicalResistanceYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChemicalResistanceYesActionPerformed

    private void InsulationNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsulationNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsulationNoActionPerformed

    private void ReinforcementNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReinforcementNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReinforcementNoActionPerformed

    private void ChemicalResistanceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChemicalResistanceNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChemicalResistanceNoActionPerformed

    private void removeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeOrderActionPerformed
        // TODO add your handling code here:
        double _pipeLength = Double.parseDouble(PipeLengthTxtBox.getText());
        double _pipeDiameter = Double.parseDouble(PipeDiameterTxtBox.getText());
        int _pipeGrade = GetPlasticGrade();
        int _pipeColor = GetColorCount(); 
        Boolean _pipeInsulation = GetInsulation();
        Boolean _pipeReinforcement = GetReinforcement();
        Boolean _pipeChemicalResistance = GetChemicalResistance();
        int _pipeQuantity = Integer.parseInt(PipeQuantityTxtBox.getText());
        
        Pipe pipe = new Pipe(_pipeLength, _pipeDiameter, _pipeGrade, _pipeColor, _pipeInsulation, _pipeReinforcement, _pipeChemicalResistance, _pipeQuantity);

        
    }//GEN-LAST:event_removeOrderActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ChemicalResistanceNo;
    private javax.swing.JRadioButton ChemicalResistanceYes;
    private javax.swing.JRadioButton Color0RadioBtn;
    private javax.swing.JRadioButton Color1RadioBtn;
    private javax.swing.JRadioButton Color2RadioBtn;
    private javax.swing.JRadioButton Grade1RadioBtn;
    private javax.swing.JRadioButton Grade2RadioBtn;
    private javax.swing.JRadioButton Grade3RadioBtn;
    private javax.swing.JRadioButton Grade4RadioBtn;
    private javax.swing.JRadioButton Grade5RadioBtn;
    private javax.swing.JRadioButton InsulationNo;
    private javax.swing.JRadioButton InsulationYes;
    private javax.swing.JTextField PipeDiameterTxtBox;
    private javax.swing.JTextField PipeLengthTxtBox;
    private javax.swing.JTextField PipeQuantityTxtBox;
    private javax.swing.JRadioButton ReinforcementNo;
    private javax.swing.JRadioButton ReinforcementYes;
    private javax.swing.JButton addOrder;
    private javax.swing.ButtonGroup colourGroup;
    private javax.swing.ButtonGroup gradeGroup;
    private javax.swing.ButtonGroup insulationGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup reinforcementGroup;
    private javax.swing.JButton removeOrder;
    private javax.swing.ButtonGroup resistanceGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
        
        LongPipes pipe = new LongPipes();
        
    }
    
           
    /** 
    * @return Get plastic radio button input.
    * @author Lee 750834
    */ 
    public int GetPlasticGrade()
    {
        if(Grade1RadioBtn.isSelected()) return 1;
        if(Grade2RadioBtn.isSelected()) return 2;
        if(Grade3RadioBtn.isSelected()) return 3;
        if(Grade4RadioBtn.isSelected()) return 4;
        if(Grade5RadioBtn.isSelected()) return 5;
        else return 1;
    }
    
    /** 
    * @return Get color radio button input.
    * @author Lee 750834
    */ 
    public int GetColorCount(){
        if(Color0RadioBtn.isSelected()) return 0;
        if(Color1RadioBtn.isSelected()) return 1;
        if(Color2RadioBtn.isSelected()) return 2;
        else return 0;
    }
    
    /** 
    * @return Get insulation state
    * @author Lee 750834
    */ 
    public Boolean GetInsulation(){
        if(InsulationYes.isSelected()) return true;
        if(InsulationNo.isSelected()) return false;
        else return false;
    }
    
    /** 
    * @return Get reinforcement state
    * @author Lee 750834
    */ 
    public Boolean GetReinforcement(){
        if(ReinforcementYes.isSelected()) return true;
        if(ReinforcementNo.isSelected()) return false;
        else return false;
    }
        
    /** 
    * @return Get chemical resistance state
    * @author Lee 750834
    */ 
    public Boolean GetChemicalResistance() {
        if(ChemicalResistanceYes.isSelected()) return true;
        if(ChemicalResistanceNo.isSelected()) return false;
        else return false;
    }

}
