/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package longpipes;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;


/**
 *
 * @author up750834
 */
public class LongPipesSystem extends javax.swing.JFrame {

    /**
     * Creates new form LongPipesSystem
     */
    public LongPipesSystem() {
        initComponents();
        DefaultForm();
        SetupBasketList();
        UpdateFormDateTime();
    }

    // 750834 Setup objects
    DefaultListModel basketModel = new DefaultListModel();
    LongPipesGUILink pipeSystem = new LongPipesGUILink();
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pipeGradeGroup = new javax.swing.ButtonGroup();
        pipeColorGroup = new javax.swing.ButtonGroup();
        jPanelStatus = new javax.swing.JPanel();
        jLabelStatus = new javax.swing.JLabel();
        jLabelStatusTime = new javax.swing.JLabel();
        jPanelOrder = new javax.swing.JPanel();
        jPanelLength = new javax.swing.JPanel();
        jLabelLength = new javax.swing.JLabel();
        jLabelLengthInfo = new javax.swing.JLabel();
        jSpinnerLength = new javax.swing.JSpinner();
        jPanelDiameter = new javax.swing.JPanel();
        jLabelDiameter = new javax.swing.JLabel();
        jLabelDiameterInfo = new javax.swing.JLabel();
        jSpinnerDiameter = new javax.swing.JSpinner();
        panelPlasticGrade = new javax.swing.JPanel();
        jRadioButtonGrade1 = new javax.swing.JRadioButton();
        jRadioButtonGrade2 = new javax.swing.JRadioButton();
        jRadioButtonGrade3 = new javax.swing.JRadioButton();
        jRadioButtonGrade4 = new javax.swing.JRadioButton();
        jRadioButtonGrade5 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonColor0 = new javax.swing.JRadioButton();
        jRadioButtonColor1 = new javax.swing.JRadioButton();
        jRadioButtonColor2 = new javax.swing.JRadioButton();
        jPanelAdditionalFeatures = new javax.swing.JPanel();
        jToggleButtonInnerInsulation = new javax.swing.JToggleButton();
        jToggleButtonOuterReinforcement = new javax.swing.JToggleButton();
        jToggleButtonChemicalResistance = new javax.swing.JToggleButton();
        jButtonClearFeatures = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelQuantity = new javax.swing.JPanel();
        jLabelQuantity = new javax.swing.JLabel();
        jSpinnerQuantity = new javax.swing.JSpinner();
        jButtonResetOrder = new javax.swing.JButton();
        jPanelInfo = new javax.swing.JPanel();
        jLabelOrderDate = new javax.swing.JLabel();
        jLabelOrderTime = new javax.swing.JLabel();
        jButtonAddOrder = new javax.swing.JButton();
        jPanelBasket = new javax.swing.JPanel();
        jPanelBasketControl = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListBasketList = new javax.swing.JList<>();
        jButtonClearBasket = new javax.swing.JButton();
        jButtonRemoveSelected = new javax.swing.JButton();
        jPanelFinalCost = new javax.swing.JPanel();
        jLabelTotalCost = new javax.swing.JLabel();
        jTextFieldOrderTotalCost = new javax.swing.JTextField();
        jLabelTotalOrders = new javax.swing.JLabel();
        jTextFieldTotalOrders = new javax.swing.JTextField();
        jLabelOrderRef = new javax.swing.JLabel();
        jTextFieldOrderRef = new javax.swing.JTextField();
        jButtonBuyOrder = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanelTopInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Long Pipes Ordering System");
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanelStatus.setBackground(new java.awt.Color(153, 72, 168));
        jPanelStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStatus.setText("READY");

        jLabelStatusTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelStatusTime.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStatusTime.setText("11:41");

        javax.swing.GroupLayout jPanelStatusLayout = new javax.swing.GroupLayout(jPanelStatus);
        jPanelStatus.setLayout(jPanelStatusLayout);
        jPanelStatusLayout.setHorizontalGroup(
            jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatusLayout.createSequentialGroup()
                .addComponent(jLabelStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelStatusTime))
        );
        jPanelStatusLayout.setVerticalGroup(
            jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStatusLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus)
                    .addComponent(jLabelStatusTime)))
        );

        jPanelOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 72, 168)));

        jPanelLength.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelLength.setText("Length of pipe:");

        jLabelLengthInfo.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabelLengthInfo.setText("Length to be set in meters");

        javax.swing.GroupLayout jPanelLengthLayout = new javax.swing.GroupLayout(jPanelLength);
        jPanelLength.setLayout(jPanelLengthLayout);
        jPanelLengthLayout.setHorizontalGroup(
            jPanelLengthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLengthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLengthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLengthLayout.createSequentialGroup()
                        .addComponent(jLabelLength)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinnerLength, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLengthLayout.createSequentialGroup()
                        .addComponent(jLabelLengthInfo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelLengthLayout.setVerticalGroup(
            jPanelLengthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLengthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLengthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLength)
                    .addComponent(jSpinnerLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLengthInfo)
                .addGap(39, 39, 39))
        );

        jPanelDiameter.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelDiameter.setText("Outer diameter:");

        jLabelDiameterInfo.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabelDiameterInfo.setText("Diameter to be set in inches");

        javax.swing.GroupLayout jPanelDiameterLayout = new javax.swing.GroupLayout(jPanelDiameter);
        jPanelDiameter.setLayout(jPanelDiameterLayout);
        jPanelDiameterLayout.setHorizontalGroup(
            jPanelDiameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiameterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDiameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDiameterLayout.createSequentialGroup()
                        .addComponent(jLabelDiameter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinnerDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDiameterLayout.createSequentialGroup()
                        .addComponent(jLabelDiameterInfo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelDiameterLayout.setVerticalGroup(
            jPanelDiameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiameterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDiameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDiameter)
                    .addComponent(jSpinnerDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDiameterInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPlasticGrade.setBorder(javax.swing.BorderFactory.createTitledBorder("Plastic Grade"));
        panelPlasticGrade.setName(""); // NOI18N

        pipeGradeGroup.add(jRadioButtonGrade1);
        jRadioButtonGrade1.setText("Grade [1]");

        pipeGradeGroup.add(jRadioButtonGrade2);
        jRadioButtonGrade2.setText("Grade [2]");

        pipeGradeGroup.add(jRadioButtonGrade3);
        jRadioButtonGrade3.setText("Grade [3]");

        pipeGradeGroup.add(jRadioButtonGrade4);
        jRadioButtonGrade4.setText("Grade [4]");

        pipeGradeGroup.add(jRadioButtonGrade5);
        jRadioButtonGrade5.setText("Grade [5]");

        javax.swing.GroupLayout panelPlasticGradeLayout = new javax.swing.GroupLayout(panelPlasticGrade);
        panelPlasticGrade.setLayout(panelPlasticGradeLayout);
        panelPlasticGradeLayout.setHorizontalGroup(
            panelPlasticGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlasticGradeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonGrade1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonGrade2)
                .addGap(12, 12, 12)
                .addComponent(jRadioButtonGrade3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonGrade4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonGrade5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPlasticGradeLayout.setVerticalGroup(
            panelPlasticGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPlasticGradeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPlasticGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonGrade1)
                    .addComponent(jRadioButtonGrade2)
                    .addComponent(jRadioButtonGrade3)
                    .addComponent(jRadioButtonGrade4)
                    .addComponent(jRadioButtonGrade5))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Color"));

        pipeColorGroup.add(jRadioButtonColor0);
        jRadioButtonColor0.setText("No Color");

        pipeColorGroup.add(jRadioButtonColor1);
        jRadioButtonColor1.setText("Colors [1]");

        pipeColorGroup.add(jRadioButtonColor2);
        jRadioButtonColor2.setText("Colors [2]");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonColor0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonColor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonColor2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonColor0)
                    .addComponent(jRadioButtonColor1)
                    .addComponent(jRadioButtonColor2))
                .addContainerGap())
        );

        jPanelAdditionalFeatures.setBorder(javax.swing.BorderFactory.createTitledBorder("Additional Features"));

        jToggleButtonInnerInsulation.setText("Inner Insulation");

        jToggleButtonOuterReinforcement.setText("Outer Reinforcement");

        jToggleButtonChemicalResistance.setText("Chemical Resistance");

        jButtonClearFeatures.setText("Clear Features");
        jButtonClearFeatures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearFeaturesActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1 Color", "12%"},
                {"2 Colors", "16%"},
                {"Inner Insulation", "13% "},
                {"Outer Reinforcement", "17%"},
                {"Chemical Resistance", "14%"}
            },
            new String [] {
                "Item", "Additional Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanelAdditionalFeaturesLayout = new javax.swing.GroupLayout(jPanelAdditionalFeatures);
        jPanelAdditionalFeatures.setLayout(jPanelAdditionalFeaturesLayout);
        jPanelAdditionalFeaturesLayout.setHorizontalGroup(
            jPanelAdditionalFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdditionalFeaturesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdditionalFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButtonInnerInsulation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonOuterReinforcement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonChemicalResistance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonClearFeatures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAdditionalFeaturesLayout.setVerticalGroup(
            jPanelAdditionalFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdditionalFeaturesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAdditionalFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAdditionalFeaturesLayout.createSequentialGroup()
                        .addComponent(jToggleButtonInnerInsulation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonOuterReinforcement)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonChemicalResistance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClearFeatures)))
                .addGap(26, 26, 26))
        );

        jPanelQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelQuantity.setText("Quantity of pipes for order:");

        javax.swing.GroupLayout jPanelQuantityLayout = new javax.swing.GroupLayout(jPanelQuantity);
        jPanelQuantity.setLayout(jPanelQuantityLayout);
        jPanelQuantityLayout.setHorizontalGroup(
            jPanelQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuantityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelQuantity)
                .addGap(18, 18, 18)
                .addComponent(jSpinnerQuantity)
                .addContainerGap())
        );
        jPanelQuantityLayout.setVerticalGroup(
            jPanelQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuantityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuantity)
                    .addComponent(jSpinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonResetOrder.setText("Reset Order");
        jButtonResetOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetOrderActionPerformed(evt);
            }
        });

        jPanelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelOrderDate.setText("Order Date: Sun 2017/04/17");

        jLabelOrderTime.setText("Order Time: 13:20:44");

        javax.swing.GroupLayout jPanelInfoLayout = new javax.swing.GroupLayout(jPanelInfo);
        jPanelInfo.setLayout(jPanelInfoLayout);
        jPanelInfoLayout.setHorizontalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelOrderDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelOrderTime)
                .addContainerGap())
        );
        jPanelInfoLayout.setVerticalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOrderDate)
                    .addComponent(jLabelOrderTime))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAddOrder.setText("Add Order");
        jButtonAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOrderLayout = new javax.swing.GroupLayout(jPanelOrder);
        jPanelOrder.setLayout(jPanelOrderLayout);
        jPanelOrderLayout.setHorizontalGroup(
            jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelPlasticGrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAdditionalFeatures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDiameter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrderLayout.createSequentialGroup()
                        .addComponent(jButtonResetOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOrderLayout.setVerticalGroup(
            jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelLength, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPlasticGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAdditionalFeatures, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonResetOrder)
                    .addComponent(jButtonAddOrder))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPlasticGrade.getAccessibleContext().setAccessibleDescription("");

        jPanelBasket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 72, 168)));

        jPanelBasketControl.setBorder(javax.swing.BorderFactory.createTitledBorder("Basket"));

        jListBasketList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Type I - [Length 15m, Diameter 10\", Quantity 12]", "Type II - [Length 43m, Diameter 3\", Quantity 25]", "Type III - [Length 18m, Diameter 2\", Quantity 33]", "Type IV - [Length 23m, Diameter 6.4\", Quantity 80]", "Type V - [Length 11m, Diameter 3.2\", Quantity 45]" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListBasketList);

        jButtonClearBasket.setText("Clear Basket");
        jButtonClearBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearBasketActionPerformed(evt);
            }
        });

        jButtonRemoveSelected.setText("Remove Selected");
        jButtonRemoveSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveSelectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBasketControlLayout = new javax.swing.GroupLayout(jPanelBasketControl);
        jPanelBasketControl.setLayout(jPanelBasketControlLayout);
        jPanelBasketControlLayout.setHorizontalGroup(
            jPanelBasketControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBasketControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBasketControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanelBasketControlLayout.createSequentialGroup()
                        .addComponent(jButtonClearBasket, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRemoveSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelBasketControlLayout.setVerticalGroup(
            jPanelBasketControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBasketControlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBasketControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClearBasket)
                    .addComponent(jButtonRemoveSelected)))
        );

        jPanelFinalCost.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelTotalCost.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTotalCost.setForeground(new java.awt.Color(51, 204, 0));
        jLabelTotalCost.setText("ORDER TOTAL:");

        jTextFieldOrderTotalCost.setEditable(false);
        jTextFieldOrderTotalCost.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldOrderTotalCost.setText("£0");
        jTextFieldOrderTotalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOrderTotalCostActionPerformed(evt);
            }
        });

        jLabelTotalOrders.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTotalOrders.setText("TOTAL ORDERS:");

        jTextFieldTotalOrders.setEditable(false);
        jTextFieldTotalOrders.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldTotalOrders.setText("0");
        jTextFieldTotalOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalOrdersActionPerformed(evt);
            }
        });

        jLabelOrderRef.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOrderRef.setText("ORDER REF:");

        jTextFieldOrderRef.setEditable(false);
        jTextFieldOrderRef.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldOrderRef.setText("003421");

        jButtonBuyOrder.setText("Buy Order");
        jButtonBuyOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuyOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFinalCostLayout = new javax.swing.GroupLayout(jPanelFinalCost);
        jPanelFinalCost.setLayout(jPanelFinalCostLayout);
        jPanelFinalCostLayout.setHorizontalGroup(
            jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFinalCostLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFinalCostLayout.createSequentialGroup()
                        .addGroup(jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOrderRef, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTotalOrders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTotalCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTotalOrders, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldOrderTotalCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jTextFieldOrderRef)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFinalCostLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonBuyOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelFinalCostLayout.setVerticalGroup(
            jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFinalCostLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOrderRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOrderRef))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalOrders)
                    .addComponent(jTextFieldTotalOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalCost)
                    .addComponent(jTextFieldOrderTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBuyOrder))
        );

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Total of pipe x:\t\t\t£10.00\nTotal of pipe y:\t\t\t£9.33\nTotal of pipe z:\t\t\t£23.45\nInner Insulation:\t\t\t£13.44\nOuter Reinforcement:\t\t\t£11.48\nChemical Resistance:\t\t\t£63.21\nTotal Cost of pipe:\t\t\t£55.99\nTotal Cost of extra:\t\t\t£33.94\nOrder Total:\t\t\t\t£140.40\n\nOrder Ref No:\t\t\t\t003421\nDate:\t\t\t\t\t17/11/2017\nTime:\t\t\t\t\t05:32:29\n\tThanks for shopping with LongPipes");
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanelBasketLayout = new javax.swing.GroupLayout(jPanelBasket);
        jPanelBasket.setLayout(jPanelBasketLayout);
        jPanelBasketLayout.setHorizontalGroup(
            jPanelBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBasketLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addComponent(jPanelBasketControl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFinalCost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelBasketLayout.setVerticalGroup(
            jPanelBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBasketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBasketControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelFinalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        jPanelTopInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 72, 168)));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("LongPipes Ordering System");

        javax.swing.GroupLayout jPanelTopInfoLayout = new javax.swing.GroupLayout(jPanelTopInfo);
        jPanelTopInfo.setLayout(jPanelTopInfoLayout);
        jPanelTopInfoLayout.setHorizontalGroup(
            jPanelTopInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopInfoLayout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(jLabel1)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        jPanelTopInfoLayout.setVerticalGroup(
            jPanelTopInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelBasket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelTopInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTopInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBasket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResetOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetOrderActionPerformed
        // Reset order form.
        DefaultForm();
    }//GEN-LAST:event_jButtonResetOrderActionPerformed

    private void jButtonClearBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearBasketActionPerformed
        // Clear basket.
        basketModel.clear();
        pipeSystem.order.orderedPipes.clear();
    }//GEN-LAST:event_jButtonClearBasketActionPerformed

    /**
     * Run once add order button clicked, takes pipe inputs and validates them
     * @author Dan 801685
     */
    private void jButtonAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddOrderActionPerformed
        // TEST
        // Send to GUI link which will validate pipe type and add new pipe to order
        double pipeLength = (Integer) jSpinnerLength.getValue();     
        double pipeDiameter = (Integer) jSpinnerDiameter.getValue();                     
        int pipeGrade = 1;
        if(jRadioButtonGrade1.isSelected() == true) {
            pipeGrade = 1;
        } else if(jRadioButtonGrade2.isSelected() == true) {
            pipeGrade = 2;
        } else if(jRadioButtonGrade3.isSelected() == true) {
            pipeGrade = 3;
        } else if(jRadioButtonGrade4.isSelected() == true) {
            pipeGrade = 4;
        } else if(jRadioButtonGrade5.isSelected() == true) {
            pipeGrade = 5;
        } 
        int pipeColors = 0;
        if(jRadioButtonColor0.isSelected() == true) {
            pipeColors = 0;
        } else if(jRadioButtonColor1.isSelected() == true) {
            pipeColors = 1;
        } else if(jRadioButtonColor2.isSelected() == true) {
            pipeColors = 2;
        }
 
        Boolean pipeInsulation = jToggleButtonInnerInsulation.isSelected();
        Boolean pipeReinforcement = jToggleButtonOuterReinforcement.isSelected();
        Boolean pipeChemicalResistance = jToggleButtonChemicalResistance.isSelected();
        int pipeQuantity = (Integer) jSpinnerQuantity.getValue();       
        
        String pipeStatusText = pipeSystem.ValidatePipe(pipeLength, pipeDiameter, pipeGrade, pipeColors, pipeInsulation, pipeReinforcement, pipeChemicalResistance, pipeQuantity);
        jLabelStatus.setText(pipeStatusText);
        //Need to get pipe string and find way of returning pipe type
        if (pipeStatusText == "Pipe is valid") {           
            basketModel.clear();
            for (int i = 0; i < pipeSystem.order.orderedPipes.size(); i++) {
                basketModel.addElement(pipeSystem.order.orderedPipes.get(i));
            }
            DefaultForm();
            updateInvoiceUI();
        }
    }//GEN-LAST:event_jButtonAddOrderActionPerformed

    private void jButtonRemoveSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveSelectedActionPerformed
        // Remove item X at list index
        int listIndex = jListBasketList.getSelectedIndex();
        System.out.println(listIndex);
        if (listIndex >= 0) {
            basketModel.remove(listIndex);
            pipeSystem.order.orderedPipes.remove((listIndex));
            updateInvoiceUI();
        }
    }//GEN-LAST:event_jButtonRemoveSelectedActionPerformed

    private void jTextFieldTotalOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalOrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalOrdersActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        UpdateFormDateTime();
    }//GEN-LAST:event_formMouseClicked

    private void jButtonClearFeaturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearFeaturesActionPerformed
        // Reset the feature toggles.
        jToggleButtonInnerInsulation.setSelected(false);
        jToggleButtonOuterReinforcement.setSelected(false);
        jToggleButtonChemicalResistance.setSelected(false);
    }//GEN-LAST:event_jButtonClearFeaturesActionPerformed

    private void jTextFieldOrderTotalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOrderTotalCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOrderTotalCostActionPerformed

    private void jButtonBuyOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuyOrderActionPerformed
        // TODO add your handling code here:
        //ADD INVOICE LIST INFORMATION GENERATION HERE
    }//GEN-LAST:event_jButtonBuyOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LongPipesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LongPipesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LongPipesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LongPipesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LongPipesSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddOrder;
    private javax.swing.JButton jButtonBuyOrder;
    private javax.swing.JButton jButtonClearBasket;
    private javax.swing.JButton jButtonClearFeatures;
    private javax.swing.JButton jButtonRemoveSelected;
    private javax.swing.JButton jButtonResetOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDiameter;
    private javax.swing.JLabel jLabelDiameterInfo;
    private javax.swing.JLabel jLabelLength;
    private javax.swing.JLabel jLabelLengthInfo;
    private javax.swing.JLabel jLabelOrderDate;
    private javax.swing.JLabel jLabelOrderRef;
    private javax.swing.JLabel jLabelOrderTime;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelStatusTime;
    private javax.swing.JLabel jLabelTotalCost;
    private javax.swing.JLabel jLabelTotalOrders;
    private javax.swing.JList<String> jListBasketList;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAdditionalFeatures;
    private javax.swing.JPanel jPanelBasket;
    private javax.swing.JPanel jPanelBasketControl;
    private javax.swing.JPanel jPanelDiameter;
    private javax.swing.JPanel jPanelFinalCost;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelLength;
    private javax.swing.JPanel jPanelOrder;
    private javax.swing.JPanel jPanelQuantity;
    private javax.swing.JPanel jPanelStatus;
    private javax.swing.JPanel jPanelTopInfo;
    private javax.swing.JRadioButton jRadioButtonColor0;
    private javax.swing.JRadioButton jRadioButtonColor1;
    private javax.swing.JRadioButton jRadioButtonColor2;
    private javax.swing.JRadioButton jRadioButtonGrade1;
    private javax.swing.JRadioButton jRadioButtonGrade2;
    private javax.swing.JRadioButton jRadioButtonGrade3;
    private javax.swing.JRadioButton jRadioButtonGrade4;
    private javax.swing.JRadioButton jRadioButtonGrade5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinnerDiameter;
    private javax.swing.JSpinner jSpinnerLength;
    private javax.swing.JSpinner jSpinnerQuantity;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldOrderRef;
    private javax.swing.JTextField jTextFieldOrderTotalCost;
    private javax.swing.JTextField jTextFieldTotalOrders;
    private javax.swing.JToggleButton jToggleButtonChemicalResistance;
    private javax.swing.JToggleButton jToggleButtonInnerInsulation;
    private javax.swing.JToggleButton jToggleButtonOuterReinforcement;
    private javax.swing.JPanel panelPlasticGrade;
    private javax.swing.ButtonGroup pipeColorGroup;
    private javax.swing.ButtonGroup pipeGradeGroup;
    // End of variables declaration//GEN-END:variables

    /** 
    * @return Default the form and clear all the fields.
    * @author Lee 750834
    */ 
    public void DefaultForm(){
        jSpinnerLength.setValue(0);
        jSpinnerDiameter.setValue(0);
        jSpinnerQuantity.setValue(0);
        jRadioButtonGrade1.setSelected(true);
        jRadioButtonColor0.setSelected(true);
        jToggleButtonInnerInsulation.setSelected(false);
        jToggleButtonOuterReinforcement.setSelected(false);
        jToggleButtonChemicalResistance.setSelected(false);
    }
    
    /** 
    * @return Update the date and time within the form every mouseclick. (cant find timers)
    * @author Lee 750834
    */ 
    public void UpdateFormDateTime(){
        Date date = new Date( );
        SimpleDateFormat _time = new SimpleDateFormat ("kk:mm");
        SimpleDateFormat _date = new SimpleDateFormat ("dd/MM//yyy");
        jLabelStatusTime.setText(_time.format(date));
        jLabelOrderTime.setText("Order Time: " + _time.format(date));
        jLabelOrderDate.setText("Order Date: " + _date.format(date));
    }
    
    /** 
    * Update the invoice UI new order information
    * @author Dan 801685
    */ 
    public void updateInvoiceUI() {
        updateTotalCost();
        updateTotalOrders();
    }
    
    /** 
    * Update the total cost label with the total order cost
    * @author Dan 801685
    */ 
    public void updateTotalCost() {
        String orderTotalCost = Double.toString(pipeSystem.orderTotalCost());
        jTextFieldOrderTotalCost.setText(orderTotalCost);
    }
    
    /** 
    * Update the total order label with the total order number
    * @author Dan 801685
    */ 
    public void updateTotalOrders() {
        String totalOrders = Integer.toString(pipeSystem.orderTotalOrders());
        jTextFieldTotalOrders.setText(totalOrders);
    }
    
    /** 
    * @return Create a new basket list model.
    * @author Lee 750834
    */ 
    public void SetupBasketList(){
        jListBasketList.setModel(basketModel);
    }

}
