/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package longpipes;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import javax.swing.DefaultListModel;

/**
 *
 * @author up750834
 */
public class LongPipesSystem extends javax.swing.JFrame {

    /**
     * Creates new form LongPipesSystem
     */
    public LongPipesSystem() {
        initComponents();
        defaultForm();
        setupBasketList();
        updateFormDateTime();
        generateOrderNumber();
    }

    // Setup objects
    DefaultListModel basketModel = new DefaultListModel();
    LongPipesGUILink pipeSystem = new LongPipesGUILink();
    private int _orderNumber;
    private static String _theDate;
    private static String _theTime;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pipeGradeGroup = new javax.swing.ButtonGroup();
        pipeColorGroup = new javax.swing.ButtonGroup();
        jPanelStatus = new javax.swing.JPanel();
        jLabelStatus = new javax.swing.JLabel();
        jLabelStatusTime = new javax.swing.JLabel();
        jPanelOrder = new javax.swing.JPanel();
        jPanelLength = new javax.swing.JPanel();
        jLabelLength = new javax.swing.JLabel();
        jLabelLengthInfo = new javax.swing.JLabel();
        jSpinnerLength = new javax.swing.JTextField();
        jPanelDiameter = new javax.swing.JPanel();
        jLabelDiameter = new javax.swing.JLabel();
        jLabelDiameterInfo = new javax.swing.JLabel();
        jSpinnerDiameter = new javax.swing.JTextField();
        panelPlasticGrade = new javax.swing.JPanel();
        jRadioButtonGrade1 = new javax.swing.JRadioButton();
        jRadioButtonGrade2 = new javax.swing.JRadioButton();
        jRadioButtonGrade3 = new javax.swing.JRadioButton();
        jRadioButtonGrade4 = new javax.swing.JRadioButton();
        jRadioButtonGrade5 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonColor0 = new javax.swing.JRadioButton();
        jRadioButtonColor1 = new javax.swing.JRadioButton();
        jRadioButtonColor2 = new javax.swing.JRadioButton();
        jPanelAdditionalFeatures = new javax.swing.JPanel();
        jButtonClearFeatures = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCheckBoxOuterReinforcement = new javax.swing.JCheckBox();
        jCheckBoxInnerInsulation = new javax.swing.JCheckBox();
        jCheckBoxChemicalResistance = new javax.swing.JCheckBox();
        jPanelQuantity = new javax.swing.JPanel();
        jLabelQuantity = new javax.swing.JLabel();
        jSpinnerQuantity = new javax.swing.JTextField();
        jButtonResetOrder = new javax.swing.JButton();
        jPanelInfo = new javax.swing.JPanel();
        jLabelOrderDate = new javax.swing.JLabel();
        jLabelOrderTime = new javax.swing.JLabel();
        jButtonAddOrder = new javax.swing.JButton();
        jPanelBasket = new javax.swing.JPanel();
        jPanelBasketControl = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListBasketList = new javax.swing.JList<>();
        jButtonClearBasket = new javax.swing.JButton();
        jButtonRemoveSelected = new javax.swing.JButton();
        jPanelFinalCost = new javax.swing.JPanel();
        jLabelTotalCost = new javax.swing.JLabel();
        jTextFieldOrderTotalCost = new javax.swing.JTextField();
        jLabelTotalOrders = new javax.swing.JLabel();
        jTextFieldTotalOrders = new javax.swing.JTextField();
        jLabelOrderRef = new javax.swing.JLabel();
        jTextFieldOrderRef = new javax.swing.JTextField();
        jButtonBuyOrder = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaInvoice = new javax.swing.JTextArea();
        jPanelTopInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Long Pipes Ordering System");
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanelStatus.setBackground(new java.awt.Color(153, 72, 168));
        jPanelStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStatus.setText("Enter your first pipe order");

        jLabelStatusTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelStatusTime.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStatusTime.setText("11:41");

        javax.swing.GroupLayout jPanelStatusLayout = new javax.swing.GroupLayout(jPanelStatus);
        jPanelStatus.setLayout(jPanelStatusLayout);
        jPanelStatusLayout.setHorizontalGroup(
            jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelStatusTime)
                .addContainerGap())
        );
        jPanelStatusLayout.setVerticalGroup(
            jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStatusLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus)
                    .addComponent(jLabelStatusTime)))
        );

        jPanelOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 72, 168)));

        jPanelLength.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelLength.setText("Length of pipe:");

        jLabelLengthInfo.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabelLengthInfo.setText("Length to be set in meters (1m to 6m)");

        jSpinnerLength.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jSpinnerLength.setText("0");
        jSpinnerLength.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinnerLengthKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelLengthLayout = new javax.swing.GroupLayout(jPanelLength);
        jPanelLength.setLayout(jPanelLengthLayout);
        jPanelLengthLayout.setHorizontalGroup(
            jPanelLengthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLengthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLengthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLengthLayout.createSequentialGroup()
                        .addComponent(jLabelLength)
                        .addGap(96, 96, 96)
                        .addComponent(jSpinnerLength, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelLengthInfo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLengthLayout.setVerticalGroup(
            jPanelLengthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLengthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLengthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLength)
                    .addComponent(jSpinnerLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLengthInfo)
                .addGap(59, 59, 59))
        );

        jPanelDiameter.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelDiameter.setText("Outer diameter:");

        jLabelDiameterInfo.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabelDiameterInfo.setText("Diameter to be set in inches (1\" to 6\")");

        jSpinnerDiameter.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jSpinnerDiameter.setText("0");
        jSpinnerDiameter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinnerDiameterKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelDiameterLayout = new javax.swing.GroupLayout(jPanelDiameter);
        jPanelDiameter.setLayout(jPanelDiameterLayout);
        jPanelDiameterLayout.setHorizontalGroup(
            jPanelDiameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiameterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDiameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDiameterLayout.createSequentialGroup()
                        .addComponent(jLabelDiameter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinnerDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelDiameterInfo))
                .addGap(66, 66, 66))
        );
        jPanelDiameterLayout.setVerticalGroup(
            jPanelDiameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiameterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDiameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDiameter)
                    .addComponent(jSpinnerDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDiameterInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPlasticGrade.setBorder(javax.swing.BorderFactory.createTitledBorder("Plastic Grade"));
        panelPlasticGrade.setName(""); // NOI18N

        pipeGradeGroup.add(jRadioButtonGrade1);
        jRadioButtonGrade1.setText("Grade [1]");

        pipeGradeGroup.add(jRadioButtonGrade2);
        jRadioButtonGrade2.setText("Grade [2]");

        pipeGradeGroup.add(jRadioButtonGrade3);
        jRadioButtonGrade3.setText("Grade [3]");

        pipeGradeGroup.add(jRadioButtonGrade4);
        jRadioButtonGrade4.setText("Grade [4]");

        pipeGradeGroup.add(jRadioButtonGrade5);
        jRadioButtonGrade5.setText("Grade [5]");

        javax.swing.GroupLayout panelPlasticGradeLayout = new javax.swing.GroupLayout(panelPlasticGrade);
        panelPlasticGrade.setLayout(panelPlasticGradeLayout);
        panelPlasticGradeLayout.setHorizontalGroup(
            panelPlasticGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlasticGradeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonGrade1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonGrade2)
                .addGap(12, 12, 12)
                .addComponent(jRadioButtonGrade3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonGrade4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonGrade5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPlasticGradeLayout.setVerticalGroup(
            panelPlasticGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPlasticGradeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPlasticGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonGrade1)
                    .addComponent(jRadioButtonGrade2)
                    .addComponent(jRadioButtonGrade3)
                    .addComponent(jRadioButtonGrade4)
                    .addComponent(jRadioButtonGrade5))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Color"));

        pipeColorGroup.add(jRadioButtonColor0);
        jRadioButtonColor0.setText("No Color");

        pipeColorGroup.add(jRadioButtonColor1);
        jRadioButtonColor1.setText("Colors [1]");

        pipeColorGroup.add(jRadioButtonColor2);
        jRadioButtonColor2.setText("Colors [2]");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonColor0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonColor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonColor2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonColor0)
                    .addComponent(jRadioButtonColor1)
                    .addComponent(jRadioButtonColor2))
                .addContainerGap())
        );

        jPanelAdditionalFeatures.setBorder(javax.swing.BorderFactory.createTitledBorder("Additional Features"));

        jButtonClearFeatures.setText("Clear Features");
        jButtonClearFeatures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearFeaturesActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1 Color", "12%"},
                {"2 Colors", "16%"},
                {"Inner Insulation", "13% "},
                {"Outer Reinforcement", "17%"},
                {"Chemical Resistance", "14%"}
            },
            new String [] {
                "Item", "Additional Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        jCheckBoxOuterReinforcement.setText("Outer Reinforcement");

        jCheckBoxInnerInsulation.setText("Inner Insulation");

        jCheckBoxChemicalResistance.setText("Chemical Resistance");

        javax.swing.GroupLayout jPanelAdditionalFeaturesLayout = new javax.swing.GroupLayout(jPanelAdditionalFeatures);
        jPanelAdditionalFeatures.setLayout(jPanelAdditionalFeaturesLayout);
        jPanelAdditionalFeaturesLayout.setHorizontalGroup(
            jPanelAdditionalFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdditionalFeaturesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdditionalFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxChemicalResistance)
                    .addComponent(jCheckBoxOuterReinforcement)
                    .addComponent(jCheckBoxInnerInsulation)
                    .addComponent(jButtonClearFeatures, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAdditionalFeaturesLayout.setVerticalGroup(
            jPanelAdditionalFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdditionalFeaturesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAdditionalFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAdditionalFeaturesLayout.createSequentialGroup()
                        .addComponent(jCheckBoxInnerInsulation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxOuterReinforcement)
                        .addGap(5, 5, 5)
                        .addComponent(jCheckBoxChemicalResistance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClearFeatures)))
                .addGap(26, 26, 26))
        );

        jPanelQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelQuantity.setText("Quantity of pipes for order:");

        jSpinnerQuantity.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jSpinnerQuantity.setText("0");
        jSpinnerQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinnerQuantityKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelQuantityLayout = new javax.swing.GroupLayout(jPanelQuantity);
        jPanelQuantity.setLayout(jPanelQuantityLayout);
        jPanelQuantityLayout.setHorizontalGroup(
            jPanelQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuantityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelQuantity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSpinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelQuantityLayout.setVerticalGroup(
            jPanelQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuantityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuantity)
                    .addComponent(jSpinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jButtonResetOrder.setText("Reset Pipe Order");
        jButtonResetOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetOrderActionPerformed(evt);
            }
        });

        jPanelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelOrderDate.setText("Order Date: Sun 2017/04/17");

        jLabelOrderTime.setText("Order Time: 13:20:44");

        javax.swing.GroupLayout jPanelInfoLayout = new javax.swing.GroupLayout(jPanelInfo);
        jPanelInfo.setLayout(jPanelInfoLayout);
        jPanelInfoLayout.setHorizontalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelOrderDate)
                .addGap(163, 163, 163)
                .addComponent(jLabelOrderTime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInfoLayout.setVerticalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOrderDate)
                    .addComponent(jLabelOrderTime))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAddOrder.setText("Add Pipe Order");
        jButtonAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOrderLayout = new javax.swing.GroupLayout(jPanelOrder);
        jPanelOrder.setLayout(jPanelOrderLayout);
        jPanelOrderLayout.setHorizontalGroup(
            jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOrderLayout.createSequentialGroup()
                        .addGroup(jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelAdditionalFeatures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelPlasticGrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelDiameter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelLength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelOrderLayout.createSequentialGroup()
                        .addComponent(jButtonResetOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );
        jPanelOrderLayout.setVerticalGroup(
            jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelLength, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelPlasticGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAdditionalFeatures, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonResetOrder)
                    .addComponent(jButtonAddOrder))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPlasticGrade.getAccessibleContext().setAccessibleDescription("");

        jPanelBasket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 72, 168)));

        jPanelBasketControl.setBorder(javax.swing.BorderFactory.createTitledBorder("Basket"));

        jScrollPane3.setViewportView(jListBasketList);

        jButtonClearBasket.setText("Clear Basket");
        jButtonClearBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearBasketActionPerformed(evt);
            }
        });

        jButtonRemoveSelected.setText("Remove Selected");
        jButtonRemoveSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveSelectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBasketControlLayout = new javax.swing.GroupLayout(jPanelBasketControl);
        jPanelBasketControl.setLayout(jPanelBasketControlLayout);
        jPanelBasketControlLayout.setHorizontalGroup(
            jPanelBasketControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBasketControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBasketControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addGroup(jPanelBasketControlLayout.createSequentialGroup()
                        .addComponent(jButtonClearBasket, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRemoveSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelBasketControlLayout.setVerticalGroup(
            jPanelBasketControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBasketControlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBasketControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClearBasket)
                    .addComponent(jButtonRemoveSelected)))
        );

        jPanelFinalCost.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelTotalCost.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTotalCost.setForeground(new java.awt.Color(51, 204, 0));
        jLabelTotalCost.setText("ORDER TOTAL:");

        jTextFieldOrderTotalCost.setEditable(false);
        jTextFieldOrderTotalCost.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldOrderTotalCost.setText("£0");

        jLabelTotalOrders.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTotalOrders.setText("TOTAL ORDERS:");

        jTextFieldTotalOrders.setEditable(false);
        jTextFieldTotalOrders.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldTotalOrders.setText("0");

        jLabelOrderRef.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOrderRef.setText("ORDER REF:");

        jTextFieldOrderRef.setEditable(false);
        jTextFieldOrderRef.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldOrderRef.setText("000000");

        jButtonBuyOrder.setText("Complete Order");
        jButtonBuyOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuyOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFinalCostLayout = new javax.swing.GroupLayout(jPanelFinalCost);
        jPanelFinalCost.setLayout(jPanelFinalCostLayout);
        jPanelFinalCostLayout.setHorizontalGroup(
            jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFinalCostLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFinalCostLayout.createSequentialGroup()
                        .addGroup(jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOrderRef, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTotalOrders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTotalCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTotalOrders, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldOrderTotalCost, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldOrderRef, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFinalCostLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonBuyOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelFinalCostLayout.setVerticalGroup(
            jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFinalCostLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOrderRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOrderRef))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalOrders)
                    .addComponent(jTextFieldTotalOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalCost)
                    .addComponent(jTextFieldOrderTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBuyOrder))
        );

        jTextAreaInvoice.setEditable(false);
        jTextAreaInvoice.setColumns(20);
        jTextAreaInvoice.setRows(5);
        jTextAreaInvoice.setText("Total of pipe x:\t\t\t£10.00\nTotal of pipe y:\t\t\t£9.33\nTotal of pipe z:\t\t\t£23.45\nInner Insulation:\t\t\t£13.44\nOuter Reinforcement:\t\t\t£11.48\nChemical Resistance:\t\t\t£63.21\nTotal Cost of pipe:\t\t\t£55.99\nTotal Cost of extra:\t\t\t£33.94\nOrder Total:\t\t\t\t£140.40\n\nOrder Ref No:\t\t\t\t003421\nDate:\t\t\t\t\t17/11/2017\nTime:\t\t\t\t\t05:32:29\n\tThanks for shopping with LongPipes");
        jScrollPane4.setViewportView(jTextAreaInvoice);

        javax.swing.GroupLayout jPanelBasketLayout = new javax.swing.GroupLayout(jPanelBasket);
        jPanelBasket.setLayout(jPanelBasketLayout);
        jPanelBasketLayout.setHorizontalGroup(
            jPanelBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBasketLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addComponent(jPanelBasketControl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFinalCost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelBasketLayout.setVerticalGroup(
            jPanelBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBasketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBasketControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelFinalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelTopInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 72, 168)));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("LongPipes Ordering System");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("GrB-1");

        javax.swing.GroupLayout jPanelTopInfoLayout = new javax.swing.GroupLayout(jPanelTopInfo);
        jPanelTopInfo.setLayout(jPanelTopInfoLayout);
        jPanelTopInfoLayout.setHorizontalGroup(
            jPanelTopInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(254, 254, 254)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTopInfoLayout.setVerticalGroup(
            jPanelTopInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTopInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTopInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelBasket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelTopInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelBasket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResetOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetOrderActionPerformed
        defaultForm();
    }//GEN-LAST:event_jButtonResetOrderActionPerformed

    private void jButtonClearBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearBasketActionPerformed
        clearBasket();
    }//GEN-LAST:event_jButtonClearBasketActionPerformed

    private void jButtonAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddOrderActionPerformed
        addNewPipeOrder();
    }//GEN-LAST:event_jButtonAddOrderActionPerformed

    private void jButtonRemoveSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveSelectedActionPerformed
        removeSelectedPipe();
    }//GEN-LAST:event_jButtonRemoveSelectedActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        updateFormDateTime();
    }//GEN-LAST:event_formMouseClicked

    private void jButtonClearFeaturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearFeaturesActionPerformed
        // Reset the feature toggles.
        jCheckBoxInnerInsulation.setSelected(false);
        jCheckBoxOuterReinforcement.setSelected(false);
        jCheckBoxChemicalResistance.setSelected(false);
    }//GEN-LAST:event_jButtonClearFeaturesActionPerformed

    private void jButtonBuyOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuyOrderActionPerformed
        // ADD INVOICE LIST INFORMATION GENERATION HERE
        // LEE WILL DO
        updateInvoiceTextArea();
    }//GEN-LAST:event_jButtonBuyOrderActionPerformed

    private void jSpinnerLengthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerLengthKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_jSpinnerLengthKeyTyped

    private void jSpinnerDiameterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerDiameterKeyTyped
                char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_jSpinnerDiameterKeyTyped

    private void jSpinnerQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerQuantityKeyTyped
                char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_jSpinnerQuantityKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LongPipesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LongPipesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LongPipesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LongPipesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LongPipesSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddOrder;
    private javax.swing.JButton jButtonBuyOrder;
    private javax.swing.JButton jButtonClearBasket;
    private javax.swing.JButton jButtonClearFeatures;
    private javax.swing.JButton jButtonRemoveSelected;
    private javax.swing.JButton jButtonResetOrder;
    private javax.swing.JCheckBox jCheckBoxChemicalResistance;
    private javax.swing.JCheckBox jCheckBoxInnerInsulation;
    private javax.swing.JCheckBox jCheckBoxOuterReinforcement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDiameter;
    private javax.swing.JLabel jLabelDiameterInfo;
    private javax.swing.JLabel jLabelLength;
    private javax.swing.JLabel jLabelLengthInfo;
    private javax.swing.JLabel jLabelOrderDate;
    private javax.swing.JLabel jLabelOrderRef;
    private javax.swing.JLabel jLabelOrderTime;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelStatusTime;
    private javax.swing.JLabel jLabelTotalCost;
    private javax.swing.JLabel jLabelTotalOrders;
    private javax.swing.JList<String> jListBasketList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAdditionalFeatures;
    private javax.swing.JPanel jPanelBasket;
    private javax.swing.JPanel jPanelBasketControl;
    private javax.swing.JPanel jPanelDiameter;
    private javax.swing.JPanel jPanelFinalCost;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelLength;
    private javax.swing.JPanel jPanelOrder;
    private javax.swing.JPanel jPanelQuantity;
    private javax.swing.JPanel jPanelStatus;
    private javax.swing.JPanel jPanelTopInfo;
    private javax.swing.JRadioButton jRadioButtonColor0;
    private javax.swing.JRadioButton jRadioButtonColor1;
    private javax.swing.JRadioButton jRadioButtonColor2;
    private javax.swing.JRadioButton jRadioButtonGrade1;
    private javax.swing.JRadioButton jRadioButtonGrade2;
    private javax.swing.JRadioButton jRadioButtonGrade3;
    private javax.swing.JRadioButton jRadioButtonGrade4;
    private javax.swing.JRadioButton jRadioButtonGrade5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jSpinnerDiameter;
    private javax.swing.JTextField jSpinnerLength;
    private javax.swing.JTextField jSpinnerQuantity;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaInvoice;
    private javax.swing.JTextField jTextFieldOrderRef;
    private javax.swing.JTextField jTextFieldOrderTotalCost;
    private javax.swing.JTextField jTextFieldTotalOrders;
    private javax.swing.JPanel panelPlasticGrade;
    private javax.swing.ButtonGroup pipeColorGroup;
    private javax.swing.ButtonGroup pipeGradeGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * @return Generates a random order number. This is just cosmetic.
     * @author Lee 750834
     */
    public void generateOrderNumber() {
        Random rand = new Random();
        _orderNumber = rand.nextInt(9999) + 1;
        jTextFieldOrderRef.setText("00" + Integer.toString(_orderNumber));
    }

    /**
     * @return Default the form and clear all the fields.
     * @author Lee 750834
     */
    public void defaultForm() {
        jSpinnerLength.setText("0");
        jSpinnerDiameter.setText("0");
        jSpinnerQuantity.setText("0");
        jRadioButtonGrade1.setSelected(true);
        jRadioButtonColor0.setSelected(true);
        jCheckBoxInnerInsulation.setSelected(false);
        jCheckBoxOuterReinforcement.setSelected(false);
        jCheckBoxChemicalResistance.setSelected(false);
    }

    /**
     * @return Update the date and time within the form every mouseclick. (cant
     * find timers)
     * @author Lee 750834
     */
    public void updateFormDateTime() {
        Date date = new Date();
        SimpleDateFormat _time = new SimpleDateFormat("kk:mm");
        SimpleDateFormat _date = new SimpleDateFormat("dd/MM//yyy");
        jLabelStatusTime.setText(_time.format(date));
        jLabelOrderTime.setText("Order Time: " + _time.format(date));
        jLabelOrderDate.setText("Order Date: " + _date.format(date));
        _theDate = _date.format(date);
        _theTime = _time.format(date);
    }

    /**
     * Update the invoice UI new order information
     *
     * @author Dan 801685
     */
    public void updateInvoiceUI() {
        updateTotalCost();
        updateTotalOrders();
    }

    /**
     * Update the invoice UI new order information
     *
     * @author Dan 801685
     */
    public void updateInvoiceTextArea() {
        jTextAreaInvoice.setText(pipeSystem.generateOrderInvoice(_orderNumber));
    }

    /**
     * Update the total cost label with the total order cost
     *
     * @author Dan 801685
     */
    public void updateTotalCost() {
        Double orderTotalCost = pipeSystem.orderTotalCost();
        String orderTotalCostString = String.format("£%.2f", orderTotalCost);
        jTextFieldOrderTotalCost.setText(orderTotalCostString);
    }

    /**
     * Update the total order label with the total order number
     *
     * @author Dan 801685
     */
    public void updateTotalOrders() {
        String totalOrders = Integer.toString(pipeSystem.orderTotalOrders());
        jTextFieldTotalOrders.setText(totalOrders);
    }

    /**
     * @return Create a new basket list model.
     * @author Lee 750834
     */
    public void setupBasketList() {
        jListBasketList.setModel(basketModel);
    }

    /**
     * @return Removes a selected pipe.
     * @author Lee 750834
     */
    public void removeSelectedPipe() {
        int listIndex = jListBasketList.getSelectedIndex();
        if (listIndex >= 0) {
            basketModel.remove(listIndex);
            ArrayList<Pipe> orderedPipes = pipeSystem.getOrderedPipes();
            orderedPipes.remove((listIndex));
            updateInvoiceUI();
        }
    }

    /**
     * @return Clear the basket and update the UI.
     * @author Lee 750834
     */
    public void clearBasket() {
        basketModel.clear();
        ArrayList<Pipe> orderedPipes = pipeSystem.getOrderedPipes();
        orderedPipes.clear();
        updateInvoiceUI();
    }

    /**
     * @return Send to link to validate pipe type and add to order.
     * @author Lee 750834
     * @author Dan 801685
     */
    public void addNewPipeOrder() {
        double pipeLength = (double) Integer.parseInt(jSpinnerLength.getText());
        double pipeDiameter = (double) Integer.parseInt(jSpinnerDiameter.getText());
        int pipeGrade = getPipeGrade();
        int pipeColors = getColours();

        Boolean pipeInsulation = jCheckBoxInnerInsulation.isSelected();
        Boolean pipeReinforcement = jCheckBoxOuterReinforcement.isSelected();
        Boolean pipeChemicalResistance = jCheckBoxChemicalResistance.isSelected();
        int pipeQuantity = Integer.parseInt(jSpinnerQuantity.getText());

        //Get better way of handling valid/invalid ui without direct string checking
        String pipeStatusText = pipeSystem.ValidatePipe(pipeLength, pipeDiameter, pipeGrade, pipeColors, pipeInsulation, pipeReinforcement, pipeChemicalResistance, pipeQuantity);
        jLabelStatus.setText(pipeStatusText);
        //Replace with get methods for order
        if ("Pipe added to basket".equals(pipeStatusText)) {
            basketModel.clear();
            ArrayList<Pipe> orderedPipes = pipeSystem.getOrderedPipes();

            for (int i = 0; i < orderedPipes.size(); i++) {  //NEW FUNCTION
                basketModel.addElement(orderedPipes.get(i).getDetails());  //NEW FUNCTION
            }
            defaultForm();
            updateInvoiceUI();
        }
    }

    /*
     * @return Grade of input pipe from the user interface input
     * @author Dan 801685
     */
    public int getPipeGrade() {
        int pipeGrade = 1;
        if (jRadioButtonGrade1.isSelected() == true) {
            pipeGrade = 1;
        } else if (jRadioButtonGrade2.isSelected() == true) {
            pipeGrade = 2;
        } else if (jRadioButtonGrade3.isSelected() == true) {
            pipeGrade = 3;
        } else if (jRadioButtonGrade4.isSelected() == true) {
            pipeGrade = 4;
        } else if (jRadioButtonGrade5.isSelected() == true) {
            pipeGrade = 5;
        }
        return pipeGrade;
    }

    /*
     * @return Number of colours of input pipe from the user interface input
     * @author Dan 801685
     */
    public int getColours() {
        int pipeColors = 0;
        if (jRadioButtonColor0.isSelected() == true) {
            pipeColors = 0;
        } else if (jRadioButtonColor1.isSelected() == true) {
            pipeColors = 1;
        } else if (jRadioButtonColor2.isSelected() == true) {
            pipeColors = 2;
        }
        return pipeColors;
    }

    public static String[] getDateTime() {
        return new String[]{_theDate, _theTime};
    }
}
